import logging
import unittest
from import_dart_data import esclient, ELASTICSEARCH_URL, ELASTIC_CERTFILE_FINGERPRINT, ELASTIC_PASSWORD, get_corp_info_from_dart
from elasticsearch import Elasticsearch
from elasticsearch.helpers import streaming_bulk, scan
import sys


class Test(unittest.TestCase):
    def setUp(self):
        # Create the client instance
        # Password for the 'elastic' user generated by Elasticsearch
        # ELASTIC_PASSWORD = "<password>"
        # self.esclient = Elasticsearch(
        #     ELASTICSEARCH_URL,
        #     # ca_certs=ELASTIC_CERTFILE,
        #     ssl_assert_fingerprint=ELASTIC_CERTFILE_FINGERPRINT,
        #     basic_auth=("elastic", ELASTIC_PASSWORD)
        # )
        self.esclient = esclient
        self.code = "00126380"
        self.corp_name = '삼성전자'

    def test_get_corp_info_from_dart(self):
        data = get_corp_info_from_dart(self.code, [2022])
        print(data)
        # self.assertIsNotNone(data)
        self.assertGreater(len(data), 0)
        
    
    def test_elasticsearch_client(self):
        info = self.esclient.info()
        print(info)
        self.assertGreater(len(info), 0)

    def test_query_id(self):
        # 삼성잔자
        self.code = "00126380"
        self.corp_name = '삼성전자'
        resp = self.esclient.get(index="corp_code", id=self.code)
        # print(resp)
        # {'_index': 'corp_code', '_id': '00126380', '_version': 1, '_seq_no': 288931, '_primary_term': 1, 
        # 'found': True, 
        # '_source': {'code': '00126380', 'corp_name': '삼성전자', 'stock_code': '005930', 'modify_date': '20230110'}}
        self.assertEqual(resp['_source']['code'], self.code)
        self.assertEqual(resp['_source']['corp_name'], self.corp_name)

    def test_query_all_docs(self):
        logging.disable(sys.maxsize)  # Python 3
        n = 0
        for doc in scan(self.esclient, query={"query": {"match_all": {}}}, index="corp_code"):
            if n == 0:
                print(doc)
            n += 1
        logging.disable(logging.NOTSET)
        self.assertEqual(n, 97568)
